export const UPDATE_ACTIVE_INDEX = 'UPDATE_ACTIVE_INDEX';
export const UPDATE_IMAGES = 'UPDATE_IMAGES';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
export const INCREASE_CURRENT_PAGE = 'INCREASE_CURRENT_PAGE';