export const UPDATE_ACTIVE_INDEX = 'UPDATE_ACTIVE_INDEX';
export const APPEND_IMAGES = 'APPEND_IMAGES';
export const PREPEND_IMAGES = 'PREPEND_IMAGES';
export const UPDATE_IMAGES = 'UPDATE_IMAGES';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
export const INCREASE_CURRENT_PAGE = 'INCREASE_CURRENT_PAGE';
export const DECREASE_CURRENT_PAGE = 'DECREASE_CURRENT_PAGE';
export const UPDATE_IS_LOADING_DATA = 'UPDATE_IS_LOADING_DATA';